name: app
name: app
type: nodejs:16

build:
  flavor: none
  commands:
    build: yarn build  # The build command

web:
  locations:
    '/':
      root: 'build/'  # Root directory for the web server
      index: true  # Ensures that index.html is served for requests to '/'
      passthru: '/index.html'  # SPA routing (optional)